# Change these first
owner: BinPar # Your GitHub organization or username, where this repository lives
repo: emp-status # The name of this repository

sites:
  - name: EMP - ES
    url: https://www.medicapanamericana.com
    headers:
      - "Cookie: filial=ES"
  - name: EMP - CO
    url: https://www.medicapanamericana.com
    headers:
      - "Cookie: filial=CO"
  - name: EMP - MX
    url: https://www.medicapanamericana.com
    headers:
      - "Cookie: filial=MX"
  - name: EMP - AR
    url: https://www.medicapanamericana.com
    headers:
      - "Cookie: filial=AR"
  - name: EMP - US
    url: https://www.medicapanamericana.com
    headers:
      - "Cookie: filial=US"

assignees: # Users to assign downtime issues (optional)
  - Mgonand

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /emp-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: EMP - Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
