# Change these first
owner: BinPar # Your GitHub organization or username, where this repository lives
repo: emp-status # The name of this repository

sites:
  - name: EMP - ES
    url: https://www.medicapanamericana.com
    headers:
      - "Cookie: filial=ES"
  - name: EMP - CO
    url: https://www.medicapanamericana.com
    headers:
      - "Cookie: filial=CO"
  - name: EMP - MX
    url: https://www.medicapanamericana.com
    headers:
      - "Cookie: filial=MX"
  - name: EMP - AR
    url: https://www.medicapanamericana.com
    headers:
      - "Cookie: filial=AR"
  - name: EMP - US
    url: https://www.medicapanamericana.com
    headers:
      - "Cookie: filial=US"

assignees: # Users to assign downtime issues (optional)
  - Mgonand

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /emp-status
  logoUrl: https://media.discordapp.net/attachments/877231732414353458/941262647599460392/unknown.png
  name: EMP - Status
  introTitle: "EMP Webs status"
  introMessage: "Total uptime for all EMP branches"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: Mgonand
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
